spring.application.name=BackendSDCC
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=create

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/my-test-realm
logging.level.org.springframework.security=TRACE

#------------PDF Genration properties---------------------
currencySymbol=?
table_noOfColumns=4
table.columnNames=Product Code, Product Name, Quantity, Price Cad., Price Tot.