spring.application.name=BackendSDCC
spring.datasource.url=jdbc:postgresql://localhost:5433/backendsdcc_dev
spring.datasource.username=sdcc
spring.datasource.password=sdcc_pass
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


# Jackson - Instant serialization (ISO-8601)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

#------------PDF Genration properties---------------------
table_noOfColumns=5
table.columnNames=Product Code, Product Name, Quantity, Price Cad., Price Tot.

aws.s3.bucket-name=backendsdcc-dev-files-001-094028239135-eu-north-1-an
aws.s3.secret-key=SECRET_RIMOSSO
aws.s3.access-key=AKIA_CHIAVE_RIMOSSA
aws.s3.region=eu-north-1


# Firebase Authentication
firebase.project-id=sdcc-a2df9
logging.level.org.springframework.security=DEBUG
