spring.application.name=BackendSDCC
spring.datasource.url=jdbc:postgresql://rds-endpoint-rimosso.invalid:5432/
spring.datasource.username=postgres
spring.datasource.password=PASSWORD_RIMOSSA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=create

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/my-test-realm
logging.level.org.springframework.security=TRACE